repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files   # bloquea archivos grandes (datasets, modelos)
        args: ["--maxkb=500"]
      - id: detect-private-key        # bloquea claves privadas
      - id: check-yaml                # YAML bien formado
      - id: check-toml                # pyproject.toml bien formado
      - id: end-of-file-fixer         # salto de línea al final del archivo
      - id: trailing-whitespace       # quita espacios sobrantes al final de línea

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.10                       # se actualiza con autoupdate (paso 3)
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format
